force-app/main/default/objects/SC_Custom_Lookup_Property__mdt/SC_Custom_Lookup_Property__mdt.object-meta.xml
<CustomObject>
    <description>Holds properties for each lookup type, which can be used to choose fields and objects, and also filter records</description>
    <label>Custom Lookup Property</label>
    <pluralLabel>Custom Lookup Properties</pluralLabel>
</CustomObject>

force-app/main/default/objects/SC_Custom_Lookup_Property__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description>The conditions which should be used for filtering the records</description>
    <label>Condition</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SC_Custom_Lookup_Property__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Store the field which needs to be used as the label for the looked up results</description>
    <label>Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SC_Custom_Lookup_Property__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Stores the name of the object which we use to query for the lookup</description>
    <label>Object</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SC_CustomComponents.cls
public with sharing class SC_CustomComponents {

    @AuraEnabled
    public static List<LookupRecordWrapper> fetchLookupRecords(String lookupName, String searchString, String filterValues) {
        String searchLike = '%' + searchString + '%';
        SC_Custom_Lookup_Property__mdt customLookupProperty = SC_Custom_Lookup_Property__mdt.getInstance(lookupName);
        if(customLookupProperty == null) {
            throw new AuraHandledException('Lookup Name is Incorrect (or) Lookup Name has not been added to the metadata');
        }
        String query = String.format('SELECT Id, {0} FROM {1} WHERE {0} LIKE :searchLike AND {0} != NULL ', new List<String>{customLookupProperty.Field__c, customLookupProperty.Object__c, searchLike });
        if(String.isNotBlank(customLookupProperty.Condition__c)) {
            query += 'AND (' + customLookupProperty.Condition__c + ') ';
        }
        query += 'LIMIT 10';
        List<sObject> recordList = new List<sObject>();
        try {
            recordList = Database.query(query);
        } catch (Exception e) {
            throw new AuraHandledException('Error Occured while searching. Error : ' + e.getMessage());
        }
        List<LookupRecordWrapper> lookupRecordList = new List<LookupRecordWrapper>();
        for(sObject record: recordList) {
            LookupRecordWrapper lookupRecord = new LookupRecordWrapper();
            lookupRecord.value = (String)record.get('Id');
            lookupRecord.label = getLabel(record, customLookupProperty.Field__c);
            lookupRecordList.add(lookupRecord);
        }
        return lookupRecordList;
    }

    public static String getLabel(sObject record, String fieldName) {
        List<String> fieldList = fieldName.split('\\.');
        sObject childObject;
        if(fieldList.size() > 1) {
            childObject = record.getSObject(fieldList[0]);
            for(Integer i = 1; i < fieldList.size() - 1; i++) {
                childObject = record.getSObject(fieldList[i]);
            }
            return (String) childObject.get(fieldList[fieldList.size() - 1]);
        }
        return (String)record.get(fieldList[0]);
    }

   

    public class LookupRecordWrapper {
        @AuraEnabled public String value;
        @AuraEnabled public String label;
    }
}